package com.example.demo.models;

import java.io.Serializable;

public class RoleResources implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resources.roleId
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resources.resourcesId
     *
     * @mbg.generated
     */
    private Integer resourcesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resources.roleId
     *
     * @return the value of role_resources.roleId
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resources.roleId
     *
     * @param roleid the value for role_resources.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resources.resourcesId
     *
     * @return the value of role_resources.resourcesId
     *
     * @mbg.generated
     */
    public Integer getResourcesid() {
        return resourcesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resources.resourcesId
     *
     * @param resourcesid the value for role_resources.resourcesId
     *
     * @mbg.generated
     */
    public void setResourcesid(Integer resourcesid) {
        this.resourcesid = resourcesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", resourcesid=").append(resourcesid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}