server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/idea_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.example.springbootmybatis.entity
  mapper-locations: classpath:/mapper/*.xml

  logging:
    level:
      com:
        example:
          springbootmybatis:
            Dao: debug