package com.example.demo.dao;

import com.example.demo.models.Customers;
import java.util.List;

public interface CustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated
     */
    int insert(Customers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customers
     *
     * @mbg.generated
     */
    List<Customers> selectAll();
}