package com.example.demo.dao;

import com.example.demo.models.HibernateSequence;
import java.util.List;

public interface HibernateSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hibernate_sequence
     *
     * @mbg.generated
     */
    int insert(HibernateSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hibernate_sequence
     *
     * @mbg.generated
     */
    List<HibernateSequence> selectAll();
}