package com.example.demo.dao;

import com.example.demo.models.RoleResources;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("roleid") Integer roleid, @Param("resourcesid") Integer resourcesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    int insert(RoleResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resources
     *
     * @mbg.generated
     */
    List<RoleResources> selectAll();
}