package com.example.demo.dao;

import com.example.demo.models.URole;
import java.util.List;

public interface URoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    int insert(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    URole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    List<URole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(URole record);
}